Repository softeerbootcamp-6th/Team2-HakdongMusician, pull requests merged in 2025-07, with the labels that each got.

#13 Docs/Common/#12/document_folder_initailize
  docs/backend/logging.md
  docs/backend/report_table_managing_discussion.md
  docs/common/meetings/daily_review_template.md
  docs/common/meetings/daily_scrum_template.md
  docs/common/meetings/week1/0728.md
  docs/common/meetings/week1/0729_scrum.md
  docs/common/meetings/weekly_review_template.md
  docs/frontend/.gitkeep
  docs/rule.md
Labels: 📄 documentation, 👨🏻‍🏫 BE - 김수환

#34 Feature/fe/#23 - Toggle / BottomSheet/ Modal / Toast 컴포넌트 구현
  daycan-front/apps/client/src/App.tsx
  daycan-front/apps/client/src/pages/TypoTest.tsx
  daycan-front/packages/ui/package.json
  daycan-front/packages/ui/src/assets/svg/circle-check.svg
  daycan-front/packages/ui/src/assets/svg/warning-filled.svg
  daycan-front/packages/ui/src/assets/svg/warning-outline.svg
  daycan-front/packages/ui/src/components/BottomSheet/BottomSheet.css.ts
  daycan-front/packages/ui/src/components/BottomSheet/BottomSheet.tsx
  daycan-front/packages/ui/src/components/BottomSheet/index.ts
  daycan-front/packages/ui/src/components/Modal/Modal.css.ts
  daycan-front/packages/ui/src/components/Modal/Modal.tsx
  daycan-front/packages/ui/src/components/Modal/index.ts
  daycan-front/packages/ui/src/components/Toast /Toast.tsx
  daycan-front/packages/ui/src/components/Toast /index.ts
  daycan-front/packages/ui/src/components/Toast /style.css.ts
  daycan-front/packages/ui/src/components/Toast /useToast.tsx
  daycan-front/packages/ui/src/components/Toggle/Toggle.css.ts
  daycan-front/packages/ui/src/components/Toggle/Toggle.tsx
  daycan-front/packages/ui/src/components/Toggle/index.ts
  daycan-front/packages/ui/src/components/index.ts
  daycan-front/pnpm-lock.yaml
Labels: 👦🏻 FE - 홍규진, ✨ feature, 🎨 style

#37 Feature/fe/#36 - Admin / Client 내에서 사용할 공통 Layout 설정
  daycan-front/apps/admin/package.json
  daycan-front/apps/admin/src/App.tsx
  daycan-front/apps/admin/src/layout/index.ts
  daycan-front/apps/admin/src/layout/main/index.ts
  daycan-front/apps/admin/src/layout/main/mainLayout.css.ts
  daycan-front/apps/admin/src/layout/main/mainLayout.tsx
  daycan-front/apps/admin/src/layout/report/index.ts
  daycan-front/apps/admin/src/layout/report/reportLayout.css.ts
  daycan-front/apps/admin/src/layout/report/reportLayout.tsx
  daycan-front/apps/admin/src/router/Route.tsx
  daycan-front/apps/admin/src/router/routes.tsx
  daycan-front/apps/client/package.json
  daycan-front/apps/client/src/App.tsx
  daycan-front/apps/client/src/layout/index.ts
  daycan-front/apps/client/src/layout/mobile/index.ts
  daycan-front/apps/client/src/layout/mobile/mobileLayout.css.ts
  daycan-front/apps/client/src/layout/mobile/mobileLayout.tsx
  daycan-front/apps/client/src/pages/TypoTest.tsx
  daycan-front/apps/client/src/pages/main/index.css.ts
  daycan-front/apps/client/src/pages/main/index.tsx
  daycan-front/apps/client/src/router/Route.tsx
  daycan-front/apps/client/src/router/routes.tsx
  daycan-front/apps/client/src/styles/reset.css
  daycan-front/packages/ui/src/components/BottomSheet/BottomSheet.css.ts
  daycan-front/packages/ui/src/components/BottomSheet/BottomSheet.tsx
  daycan-front/packages/ui/src/components/Modal/Modal.css.ts
  daycan-front/packages/ui/src/components/Modal/Modal.tsx
  daycan-front/pnpm-lock.yaml
  daycan-front/pnpm-workspace.yaml
Labels: 👦🏻 FE - 홍규진, ✨ feature, 🎨 style

#43 Feature/fe/#38 디자인 시스템 최종점검 과 segemet 컴포넌트 제작
  daycan-front/apps/client/src/pages/ComponentTest.tsx
  daycan-front/packages/ui/src/components/Button/Button.tsx
  daycan-front/packages/ui/src/components/Chip/Chip.css.ts
  daycan-front/packages/ui/src/components/Chip/Chip.tsx
  daycan-front/packages/ui/src/components/Input/Input.css.ts
  daycan-front/packages/ui/src/components/Input/Input.tsx
  daycan-front/packages/ui/src/components/Segment/ChipSegment/ChipSegment.tsx
  daycan-front/packages/ui/src/components/Segment/ChipSegment/index.ts
  daycan-front/packages/ui/src/components/Segment/ItemSegment/ItemSegment.tsx
  daycan-front/packages/ui/src/components/Segment/ItemSegment/SegmentItem/SegmentItem.css.ts
  daycan-front/packages/ui/src/components/Segment/ItemSegment/SegmentItem/SegmentItem.tsx
  daycan-front/packages/ui/src/components/Segment/ItemSegment/SegmentItem/index.ts
  daycan-front/packages/ui/src/components/Segment/ItemSegment/index.ts
  daycan-front/packages/ui/src/components/Segment/Segment.css.ts
  daycan-front/packages/ui/src/components/Segment/Segment.tsx
  daycan-front/packages/ui/src/components/Segment/index.ts
  daycan-front/packages/ui/src/components/index.ts
  daycan-front/packages/ui/src/utils/customWidthHeightType.ts
  daycan-front/packages/ui/src/utils/index.ts
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature

#45 Feature/fe/#44 Chip 컴포넌트 && Segment 컴포넌트 리팩토링
  daycan-front/apps/client/src/pages/ComponentTest.tsx
  daycan-front/apps/client/src/pages/TypoTest.tsx
  daycan-front/packages/ui/src/components/Chip/Chip.css.ts
  daycan-front/packages/ui/src/components/Chip/Chip.tsx
  daycan-front/packages/ui/src/components/Segment/ChipSegment/ChipSegment.tsx
  daycan-front/packages/ui/src/components/Segment/ChipSegment/index.ts
  daycan-front/packages/ui/src/components/Segment/ItemSegment/ItemSegment.tsx
  daycan-front/packages/ui/src/components/Segment/ItemSegment/SegmentItem/SegmentItem.css.ts
  daycan-front/packages/ui/src/components/Segment/ItemSegment/index.ts
  daycan-front/packages/ui/src/components/Segment/Segment.css.ts
  daycan-front/packages/ui/src/components/Segment/Segment.tsx
  daycan-front/packages/ui/src/components/Segment/SegmentItem/SegmentItem.css.ts
  daycan-front/packages/ui/src/components/Segment/SegmentItem/SegmentItem.tsx
  daycan-front/packages/ui/src/components/Segment/SegmentItem/index.ts
Labels: 👱🏻‍♂️ FE - 소보길
