Repository softeerbootcamp-6th/Team2-HakdongMusician, pull requests merged in 2025-08, with the labels that each got.

#47 Feature/be/#26 어드민 UI 컨트롤러 스키마 제공
  daycan-back/api/src/main/java/com/daycan/adapter/HealthCheckController.java
  daycan-back/api/src/main/java/com/daycan/adapter/admin/AdminCareReportController.java
  daycan-back/api/src/main/java/com/daycan/adapter/admin/AdminCareSheetController.java
  daycan-back/api/src/main/java/com/daycan/adapter/admin/AdminCenterController.java
  daycan-back/api/src/main/java/com/daycan/adapter/admin/AdminController.java
  daycan-back/api/src/main/java/com/daycan/adapter/admin/AdminDocumentController.java
  daycan-back/api/src/main/java/com/daycan/adapter/admin/AdminMemberController.java
  daycan-back/api/src/main/java/com/daycan/adapter/member/CareSheetController.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/AdminRequest.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/AdminResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/CareReportCountResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/CareSheetCountResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/CareSheetResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/CenterResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/DocumentCountResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/DocumentStatusResponse.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/MemberRequest.java
  daycan-back/api/src/main/java/com/daycan/application/admin/dto/UrlResponse.java
  daycan-back/api/src/main/java/com/daycan/application/common/dto/MemberResponse.java
  daycan-back/api/src/main/java/com/daycan/domain/enums/CareReportStatus.java
  daycan-back/api/src/main/java/com/daycan/domain/enums/CareSheetStatus.java
  daycan-back/api/src/main/java/com/daycan/domain/enums/DocumentStatus.java
  daycan-back/api/src/main/java/com/daycan/domain/enums/Gender.java
  daycan-back/api/src/main/java/com/daycan/domain/enums/Role.java
  daycan-back/api/src/main/resources/application-develop.yml
Labels: 🧔🏻‍♂️ BE - 김동성, ✨ feature

#68 Feature/fe/#51 - 데일리 리포트 페이지 퍼블리싱
  daycan-front/apps/admin/src/components/Sidebar/Sidebar.tsx
  daycan-front/apps/admin/src/constants/iconNames.ts
  daycan-front/apps/admin/src/layout/login/LoginLayout.css.ts
  daycan-front/apps/admin/src/layout/login/LoginLayout.tsx
  daycan-front/apps/admin/src/router/routes.tsx
  daycan-front/apps/client/package.json
  daycan-front/apps/client/src/components/SemiCircularGaugeChart/SemiCircularGaugeChart.tsx
  daycan-front/apps/client/src/components/UpDownIcon/UpDownIcon.css.ts
  daycan-front/apps/client/src/components/UpDownIcon/UpDownIcon.tsx
  daycan-front/apps/client/src/components/UpDownIcon/index.ts
  daycan-front/apps/client/src/components/index.ts
  daycan-front/apps/client/src/pages/index.ts
  daycan-front/apps/client/src/pages/main/components/SummaryCard/SummaryCard.tsx
  daycan-front/apps/client/src/pages/report/ReportPage.css.ts
  daycan-front/apps/client/src/pages/report/ReportPage.tsx
  daycan-front/apps/client/src/pages/report/components/CardLayout/CardLayout.css.ts
  daycan-front/apps/client/src/pages/report/components/CardLayout/CardLayout.tsx
  daycan-front/apps/client/src/pages/report/components/CardLayout/index.ts
  daycan-front/apps/client/src/pages/report/components/CognitiveCard/CognitiveCard.tsx
  daycan-front/apps/client/src/pages/report/components/CognitiveCard/index.ts
  daycan-front/apps/client/src/pages/report/components/HealthCheckCard/HealthCheckCard.tsx
  daycan-front/apps/client/src/pages/report/components/HealthCheckCard/index.ts
  daycan-front/apps/client/src/pages/report/components/HealthImproveCard/HealthImproveCard.tsx
  daycan-front/apps/client/src/pages/report/components/HealthImproveCard/index.ts
  daycan-front/apps/client/src/pages/report/components/HealthIndexCard/HealthIndexCard.css.ts
  daycan-front/apps/client/src/pages/report/components/HealthIndexCard/HealthIndexCard.tsx
  daycan-front/apps/client/src/pages/report/components/HealthIndexCard/index.ts
  daycan-front/apps/client/src/pages/report/components/IndexColumn/IndexColumn.css.ts
  daycan-front/apps/client/src/pages/report/components/IndexColumn/IndexColumn.tsx
  daycan-front/apps/client/src/pages/report/components/IndexColumn/index.ts
  daycan-front/apps/client/src/pages/report/components/IndexRow/IndexRow.css.ts
  daycan-front/apps/client/src/pages/report/components/IndexRow/IndexRow.tsx
  daycan-front/apps/client/src/pages/report/components/IndexRow/index.ts
  daycan-front/apps/client/src/pages/report/components/MealCard/MealCard.tsx
  daycan-front/apps/client/src/pages/report/components/MealCard/index.ts
  daycan-front/apps/client/src/pages/report/components/StackCard/RotateCard.tsx
  daycan-front/apps/client/src/pages/report/components/StackCard/StackCard.css.ts
  daycan-front/apps/client/src/pages/report/components/StackCard/StackCard.tsx
  daycan-front/apps/client/src/pages/report/components/StackCard/index.ts
  daycan-front/apps/client/src/pages/report/components/StackCard/types.ts
  daycan-front/apps/client/src/pages/report/components/index.ts
  daycan-front/apps/client/src/pages/report/index.ts
  daycan-front/apps/client/src/router/routes.tsx
  daycan-front/packages/ui/src/assets/index.ts
  daycan-front/packages/ui/src/assets/svg/activity.svg
  daycan-front/packages/ui/src/assets/svg/arrow-up.svg
  daycan-front/packages/ui/src/assets/svg/brain.svg
  daycan-front/packages/ui/src/assets/svg/health.svg
  daycan-front/packages/ui/src/assets/svg/meal.svg
  daycan-front/packages/ui/src/assets/svg/stamp-bad.svg
  daycan-front/packages/ui/src/assets/svg/stamp-good.svg
  daycan-front/packages/ui/src/components/Icon/index.types.ts
  daycan-front/pnpm-lock.yaml
  daycan-front/pnpm-workspace.yaml
Labels: 👦🏻 FE - 홍규진, ✨ feature

#77 Chore/be/ - 기록지, 리포트 관련 api 명세 수정
  daycan-back/api/src/main/java/com/daycan/controller/admin/AdminCareReportController.java
  daycan-back/api/src/main/java/com/daycan/controller/admin/AdminDocumentController.java
  daycan-back/api/src/main/java/com/daycan/controller/member/MemberReportController.java
  daycan-back/api/src/main/java/com/daycan/dto/FullReportDto.java
  daycan-back/api/src/main/java/com/daycan/dto/ReportEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/member/report/HealthSupportResponse.java
  daycan-back/api/src/main/resources/application-develop.yml
Labels: 👨🏻‍🏫 BE - 김수환

#81 Feature/fe/#76 - 통계 페이지 퍼블리싱
  daycan-front/apps/client/src/layout/index.ts
  daycan-front/apps/client/src/layout/login/index.ts
  daycan-front/apps/client/src/layout/login/loginLayout.css.ts
  daycan-front/apps/client/src/layout/login/loginLayout.tsx
  daycan-front/apps/client/src/layout/main/mainLayout.css.ts
  daycan-front/apps/client/src/layout/mobile/mobileLayout.css.ts
  daycan-front/apps/client/src/pages/index.ts
  daycan-front/apps/client/src/pages/login/LoginPage.css.ts
  daycan-front/apps/client/src/pages/main/MainPage.css.ts
  daycan-front/apps/client/src/pages/main/components/Greeting/Greeting.css.ts
  daycan-front/apps/client/src/pages/main/components/RecordCheckCard/RecordCheckCard.css.ts
  daycan-front/apps/client/src/pages/main/components/RecordCheckCard/RecordCheckCard.tsx
  daycan-front/apps/client/src/pages/main/components/SummaryCard/SummaryCard.css.ts
  daycan-front/apps/client/src/pages/statistics/StatisticsPage.css.ts
  daycan-front/apps/client/src/pages/statistics/StatisticsPage.tsx
  daycan-front/apps/client/src/pages/statistics/components/BarChart/BarChart.css.ts
  daycan-front/apps/client/src/pages/statistics/components/BarChart/BarChart.tsx
  daycan-front/apps/client/src/pages/statistics/components/BarChart/CustomTooltip.css.ts
  daycan-front/apps/client/src/pages/statistics/components/BarChart/CustomTooltip.tsx
  daycan-front/apps/client/src/pages/statistics/components/BarChart/index.ts
  daycan-front/apps/client/src/pages/statistics/components/ChartLayout/ChartLayout.css.ts
  daycan-front/apps/client/src/pages/statistics/components/ChartLayout/ChartLayout.tsx
  daycan-front/apps/client/src/pages/statistics/components/ChartLayout/index.ts
  daycan-front/apps/client/src/pages/statistics/components/LineChart/CustomTooltip.css.ts
  daycan-front/apps/client/src/pages/statistics/components/LineChart/CustomTooltip.tsx
  daycan-front/apps/client/src/pages/statistics/components/LineChart/LineChart.css.ts
  daycan-front/apps/client/src/pages/statistics/components/LineChart/LineChart.tsx
  daycan-front/apps/client/src/pages/statistics/components/LineChart/index.ts
  daycan-front/apps/client/src/pages/statistics/components/RangeViolationIndicator/RangeViolationIndicator.css.ts
  daycan-front/apps/client/src/pages/statistics/components/RangeViolationIndicator/RangeViolationIndicator.tsx
  daycan-front/apps/client/src/pages/statistics/components/RangeViolationIndicator/index.ts
  daycan-front/apps/client/src/pages/statistics/components/index.ts
  daycan-front/apps/client/src/pages/statistics/constants/dummy.ts
  daycan-front/apps/client/src/pages/statistics/hooks/index.ts
  daycan-front/apps/client/src/pages/statistics/hooks/useStatistics.ts
  daycan-front/apps/client/src/pages/statistics/index.ts
  daycan-front/apps/client/src/pages/statistics/utils/chartUtils.ts
  daycan-front/apps/client/src/pages/statistics/utils/dataParser.ts
  daycan-front/apps/client/src/pages/statistics/utils/dateUtils.ts
  daycan-front/apps/client/src/pages/statistics/utils/index.ts
  daycan-front/apps/client/src/pages/statistics/utils/rangeUtils.ts
  daycan-front/apps/client/src/router/routes.tsx
Labels: 👦🏻 FE - 홍규진, ✨ feature

#80 Feature/be/#78 로그인 기능 구현 및 요청 인증 필터 구현 (초기)
  daycan-back/api/build.gradle
  daycan-back/api/src/main/java/com/daycan/auth/AuthExampleController.java
  daycan-back/api/src/main/java/com/daycan/auth/annotation/AuthenticatedUser.java
  daycan-back/api/src/main/java/com/daycan/auth/dto/LoginRequest.java
  daycan-back/api/src/main/java/com/daycan/auth/dto/LoginResponse.java
  daycan-back/api/src/main/java/com/daycan/auth/dto/ReissueRequest.java
  daycan-back/api/src/main/java/com/daycan/auth/dto/Token.java
  daycan-back/api/src/main/java/com/daycan/auth/entity/BannedToken.java
  daycan-back/api/src/main/java/com/daycan/auth/entity/RefreshToken.java
  daycan-back/api/src/main/java/com/daycan/auth/model/AuthPrincipal.java
  daycan-back/api/src/main/java/com/daycan/auth/model/CenterPrincipal.java
  daycan-back/api/src/main/java/com/daycan/auth/model/MemberPrincipal.java
  daycan-back/api/src/main/java/com/daycan/auth/model/TokenType.java
  daycan-back/api/src/main/java/com/daycan/auth/model/UserType.java
  daycan-back/api/src/main/java/com/daycan/auth/repository/BannedTokenRepository.java
  daycan-back/api/src/main/java/com/daycan/auth/repository/RefreshTokenRepository.java
  daycan-back/api/src/main/java/com/daycan/auth/security/JwtTokenProvider.java
  daycan-back/api/src/main/java/com/daycan/auth/security/filter/JwtAuthFilter.java
  daycan-back/api/src/main/java/com/daycan/auth/security/filter/LoginFilter.java
  daycan-back/api/src/main/java/com/daycan/auth/security/resolver/AuthenticatedUserArgumentResolver.java
  daycan-back/api/src/main/java/com/daycan/auth/service/AuthService.java
  daycan-back/api/src/main/java/com/daycan/auth/service/BlacklistService.java
  daycan-back/api/src/main/java/com/daycan/auth/service/TokenService.java
  daycan-back/api/src/main/java/com/daycan/common/logging/WebConfig.java
  daycan-back/api/src/main/java/com/daycan/common/response/status/AuthErrorStatus.java
  daycan-back/api/src/main/java/com/daycan/config/FilterConfig.java
  daycan-back/api/src/main/java/com/daycan/config/SwaggerConfig.java
  daycan-back/api/src/main/java/com/daycan/config/WebConfig.java
  daycan-back/api/src/main/resources/application-develop.yml
Labels: 👨🏻‍🏫 BE - 김수환

#86 feature/be/#84 부족한api 명세 작성
  daycan-back/api/src/main/java/com/daycan/controller/admin/AdminCareReportController.java
  daycan-back/api/src/main/java/com/daycan/controller/admin/AdminCareSheetController.java
  daycan-back/api/src/main/java/com/daycan/controller/member/MemberReportController.java
  daycan-back/api/src/main/java/com/daycan/controller/member/MemberStatisticsController.java
  daycan-back/api/src/main/java/com/daycan/dto/admin/request/CareSheetRequest.java
  daycan-back/api/src/main/java/com/daycan/dto/admin/request/ReportReviewRequest.java
  daycan-back/api/src/main/java/com/daycan/dto/admin/response/CareReportResponse.java
  daycan-back/api/src/main/java/com/daycan/dto/admin/response/CareSheetResponse.java
  daycan-back/api/src/main/java/com/daycan/dto/entry/CognitiveEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/entry/HealthCareEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/entry/MealSupport.java
  daycan-back/api/src/main/java/com/daycan/dto/entry/PhysicalEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/entry/ProgramEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/entry/RecoveryProgramEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/member/statistics/DailyHealthStatisticsEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/member/statistics/HealthStatisticsEntry.java
  daycan-back/api/src/main/java/com/daycan/dto/member/statistics/MemberStatisticsResponse.java
  daycan-back/api/src/main/java/com/daycan/dto/member/statistics/MonthlyHealthStatisticsEntry.java
Labels: 👨🏻‍🏫 BE - 김수환, ✨ feature

#96 Update README.md
  daycan-front/README.md
Labels: 📄 documentation, 👦🏻 FE - 홍규진, 👱🏻‍♂️ FE - 소보길

#98 Feature/fe/#82 - 모바일 종사자 기록지 입력 - home-funnel 및 info-funnel 구현을 통한 atomic 상태관리법 정의
  daycan-front/apps/admin/package.json
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/HomeFunnelStepContainer.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/atoms/homeAtom.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/Step0/Step0.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/Step1/Step1.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/types/homeType.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/utils/parseData.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/InfoFunnelStepContainer.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/atoms/infoAtom.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/InfoFunnelHeader/InfoFunnelHeader.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/InfoFunnelHeader/InfoFunnelHeader.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/InfoFunnelHeader/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/InfoFunnelLayout/InfoFunnelLayout.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/InfoFunnelLayout/InfoFunnelLayout.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/InfoFunnelLayout/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberList/MemberList.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberList/MemberList.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberList/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberList/types.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberListItem/MemberListItem.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberListItem/MemberListItem.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberListItem/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/constants/dummy.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step0/Step0.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step0/Step0.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step0/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step1/Step1.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step1/Step1.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step1/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step2/Step2.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step2/Step2.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step2/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step3/Step3.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step3/Step3.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step3/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step4/Step4.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step4/Step4.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step4/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step5/Step5.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step5/Step5.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step5/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/types/infoType.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/utils/formatDateTime.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/utils/parsingData.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/molecule/finalMolecule.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/types/careSheetType.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/utils/atomUtil.ts
  daycan-front/packages/ui/src/assets/index.ts
  daycan-front/packages/ui/src/assets/svg/block.svg
  daycan-front/packages/ui/src/assets/svg/transportation.svg
  daycan-front/packages/ui/src/components/Button/Button.css.ts
  daycan-front/packages/ui/src/components/Button/Button.tsx
  daycan-front/packages/ui/src/components/Icon/index.types.ts
  daycan-front/packages/ui/src/components/TimePicker/TimePicker.css.ts
  daycan-front/packages/ui/src/components/TimePicker/TimePicker.tsx
  daycan-front/packages/ui/src/components/TimePicker/index.ts
  daycan-front/packages/ui/src/components/index.ts
  daycan-front/pnpm-lock.yaml
  daycan-front/pnpm-workspace.yaml
Labels: 👦🏻 FE - 홍규진, ✨ feature

#108 Feature/fe/#82 - FunnelProvider 확장 및 사진 등록 페이지 퍼블리싱
  daycan-front/apps/admin/src/pages/care-sheet/funnels/diagnosis-funnel/DiagnosisFunnelStepContainer.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/diagnosis-funnel/constants/diagnosis.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/diagnosis-funnel/steps/Step0/Step0.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/diagnosis-funnel/steps/Step3/useStep3.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/diagnosis-funnel/utils/parsingData.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/HomeFunnelStepContainer.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/PhotoSelectBottomSheet/PhotoSelectBottomSheet.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/PhotoSelectBottomSheet/PhotoSelectBottomSheet.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/PhotoSelectBottomSheet/usePhotoSelect.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/Step0/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/Step1/Step1.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/Step1/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/types/homeType.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/utils/parseData.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/InfoFunnelStepContainer.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step0/Step0.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step1/Step1.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step2/Step2.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step3/Step3.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step5/Step5.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/types/infoType.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/utils/formatDateTime.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/utils/parsingData.ts
  daycan-front/packages/hooks/src/useFunnel/FunnelProvider.tsx
  daycan-front/packages/ui/src/assets/svg/add-photo-by-camera.svg
  daycan-front/packages/ui/src/assets/svg/add-photo.svg
  daycan-front/packages/ui/src/components/Icon/index.types.ts
  daycan-front/packages/ui/src/components/TimePicker/TimePicker.tsx
Labels: 👦🏻 FE - 홍규진, ✨ feature

#117 Feature/fe/#110 - 수급자 등록 페이지를 이용한 수정 페이지 퍼블리싱
  daycan-front/apps/admin/src/constants/memberDummyData.ts
  daycan-front/apps/admin/src/layout/login/LoginLayout.css.ts
  daycan-front/apps/admin/src/layout/main/mainLayout.css.ts
  daycan-front/apps/admin/src/pages/login/LoginPage.css.ts
  daycan-front/apps/admin/src/pages/member-register/MemberRegisterPage.tsx
  daycan-front/apps/admin/src/pages/member-register/components/AcceptReportInfoModal/AcceptReportInfoModal.tsx
  daycan-front/apps/admin/src/pages/member-register/components/AcceptReportInfoModal/index.ts
  daycan-front/apps/admin/src/pages/member-register/components/GuardianInfoSection/GuardianInfoSection.tsx
  daycan-front/apps/admin/src/pages/member-register/components/InfoSectionLayout/InfoSectionLayout.tsx
  daycan-front/apps/admin/src/pages/member-register/components/InfoSectionRow/InfoSectionRow.tsx
  daycan-front/apps/admin/src/pages/member-register/components/MemberInfoSection/MemberInfoSection.tsx
  daycan-front/apps/admin/src/pages/member-register/components/ReportConsentModal/index.ts
  daycan-front/apps/admin/src/pages/member-register/components/index.ts
  daycan-front/apps/admin/src/pages/member-register/hooks/useImageController.ts
  daycan-front/apps/admin/src/pages/member-register/hooks/useMemberRegisterForm.ts
  daycan-front/apps/admin/src/pages/member/MemberPage.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItemDetail/MemberDataItemDetail.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDataItemDetail/MemberDataItemDetail.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItems/MemberDataItems.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDataItems/MemberDataItems.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItems/index.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDataList/MemberDataList.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDataList/MemberDataList.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataListHeader/MemberDataListHeader.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDeleteConfirmModal/MemberDeleteConfirmModal.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDeleteConfirmModal/MemberDeleteConfirmModal.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDeleteConfirmModal/index.ts
  daycan-front/apps/admin/src/pages/member/components/MemberEditAuthModal/MemberEditAuthModal.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberEditAuthModal/MemberEditAuthModal.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberEditAuthModal/index.ts
  daycan-front/apps/admin/src/pages/member/components/index.ts
  daycan-front/apps/admin/src/pages/member/hooks/useMember.ts
  daycan-front/apps/admin/src/router/routes.tsx
  daycan-front/apps/admin/src/types/member.ts
  daycan-front/apps/admin/src/utils/util.ts
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature

#119 Feature/fe/#109 - 기록지 및 리포트 내역 모아보기 기능 구현
  daycan-front/apps/admin/src/components/CareSheetDataSummaryCard/CareSheetDataSummaryCard.css.ts
  daycan-front/apps/admin/src/components/CareSheetDataSummaryCard/CareSheetDataSummaryCard.tsx
  daycan-front/apps/admin/src/components/CareSheetDataSummaryCard/index.ts
  daycan-front/apps/admin/src/components/CareSheetDataView/CareSheetDataView.tsx
  daycan-front/apps/admin/src/components/CareSheetDataView/index.ts
  daycan-front/apps/admin/src/components/ReportDataView/ReportDataView.css.ts
  daycan-front/apps/admin/src/components/ReportDataView/ReportDataView.tsx
  daycan-front/apps/admin/src/components/ReportDataView/index.ts
  daycan-front/apps/admin/src/components/index.ts
  daycan-front/apps/admin/src/index.tsx
  daycan-front/apps/admin/src/pages/care-sheet/components/CareSheetListItem/CareSheetListItem.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step1/Step1.tsx
  daycan-front/apps/admin/src/pages/login/LoginPage.tsx
  daycan-front/apps/admin/src/pages/member/components/HistoryModal/HistoryModal.css.ts
  daycan-front/apps/admin/src/pages/member/components/HistoryModal/HistoryModal.tsx
  daycan-front/apps/admin/src/pages/member/components/HistoryModal/index.ts
  daycan-front/apps/admin/src/pages/member/components/HistoryModal/useHistoryModal.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDataItemDetail/MemberDataItemDetail.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDeleteConfirmModal/MemberDeleteConfirmModal.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberEditAuthModal/MemberEditAuthModal.css.ts
  daycan-front/apps/admin/src/router/routes.tsx
  daycan-front/apps/client/src/pages/daily-report/components/CardLayout/CardLayout.tsx
  daycan-front/apps/client/src/pages/daily-report/components/HealthIndexCard/HealthIndexCard.tsx
  daycan-front/apps/client/src/pages/login/LoginPage.tsx
  daycan-front/apps/client/src/pages/login/components/ForgotCredentialsModal/ForgotCredentialsModal.css.ts
  daycan-front/apps/client/src/pages/main/components/InfoModal/InfoModal.css.ts
  daycan-front/apps/client/src/pages/main/components/InfoModal/InfoModal.tsx
  daycan-front/packages/ui/src/components/Modal/Modal.css.ts
  daycan-front/packages/ui/src/components/Modal/Modal.tsx
Labels: 👦🏻 FE - 홍규진, ✨ feature

#148 Feature/be/#132 리포트 관련 api
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterCareReportController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterCareSheetController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterImageController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterMemberController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterOcrController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/member/MemberController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/member/MemberReportController.java
  daycan-back/api/src/main/java/com/daycan/api/dto/center/response/image/OcrResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/MemberHomeResponse.java
  daycan-back/api/src/main/java/com/daycan/common/response/status/error/CommonErrorStatus.java
  daycan-back/api/src/main/java/com/daycan/common/response/status/error/DocumentErrorStatus.java
  daycan-back/api/src/main/java/com/daycan/domain/Account.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/Center.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/Member.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/document/CareReport.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/document/CareSheet.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/document/Meal.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/document/PersonalProgram.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/document/Vital.java
  daycan-back/api/src/main/java/com/daycan/domain/entity/document/VitalAggregate.java
  daycan-back/api/src/main/java/com/daycan/domain/entry/document/sheet/MealSupport.java
  daycan-back/api/src/main/java/com/daycan/domain/entry/member/MemberMetaEntry.java
  daycan-back/api/src/main/java/com/daycan/domain/enums/MealAmount.java
  daycan-back/api/src/main/java/com/daycan/domain/model/CareReportInit.java
  daycan-back/api/src/main/java/com/daycan/domain/model/CareReportView.java
  daycan-back/api/src/main/java/com/daycan/domain/model/CareSheetInitRow.java
  daycan-back/api/src/main/java/com/daycan/domain/model/CareSheetInitVO.java
  daycan-back/api/src/main/java/com/daycan/domain/model/CareSheetView.java
  daycan-back/api/src/main/java/com/daycan/domain/model/DocumentMetaView.java
  daycan-back/api/src/main/java/com/daycan/domain/model/MemberWeeklyScoreView.java
  daycan-back/api/src/main/java/com/daycan/domain/model/ProgramNote.java
  daycan-back/api/src/main/java/com/daycan/domain/model/ReportReview.java
  daycan-back/api/src/main/java/com/daycan/domain/model/ReportWithDto.java
  daycan-back/api/src/main/java/com/daycan/external/S3Service.java
  daycan-back/api/src/main/java/com/daycan/external/storage/S3Service.java
  daycan-back/api/src/main/java/com/daycan/external/storage/StorageService.java
  daycan-back/api/src/main/java/com/daycan/repository/jpa/CareReportRepository.java
  daycan-back/api/src/main/java/com/daycan/repository/jpa/VitalRepository.java
  daycan-back/api/src/main/java/com/daycan/repository/query/DocumentQueryRepositoryImpl.java
  daycan-back/api/src/main/java/com/daycan/repository/query/StatisticsQueryRepository.java
  daycan-back/api/src/main/java/com/daycan/repository/query/StatisticsQueryRepositoryImpl.java
  daycan-back/api/src/main/java/com/daycan/service/document/CareReportService.java
  daycan-back/api/src/main/java/com/daycan/service/document/CareSheetCommandService.java
  daycan-back/api/src/main/java/com/daycan/service/document/CareSheetWriteService.java
  daycan-back/api/src/main/java/com/daycan/service/document/CenterDocumentFacade.java
  daycan-back/api/src/main/java/com/daycan/service/document/DocumentService.java
  daycan-back/api/src/main/java/com/daycan/service/document/VitalService.java
  daycan-back/api/src/main/java/com/daycan/service/member/MemberFacade.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/CareReportPrefiller.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/MealCommenter.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/MealScorer.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/ProgramCommenter.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/ProgramScorer.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/VitalCommenter.java
  daycan-back/api/src/main/java/com/daycan/util/prefiller/VitalScorer.java
  daycan-back/api/src/main/java/com/daycan/util/resolver/ReportEntryResolver.java
  daycan-back/api/src/main/java/com/daycan/util/resolver/ReportReviewAssembler.java
  daycan-back/api/src/main/java/com/daycan/util/resolver/SheetMapper.java
Labels: 👨🏻‍🏫 BE - 김수환

#151 Feature/be/#144 presigned url 생성해서 반환
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterCareReportController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterCareSheetController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterDocumentController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/center/CenterImageController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/member/MemberController.java
  daycan-back/api/src/main/java/com/daycan/api/controller/member/MemberStatisticsController.java
  daycan-back/api/src/main/java/com/daycan/api/dto/center/response/report/CareReportResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/MemberReportResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/MemberStatisticsResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/report/HealthSupportResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/report/MealSupportResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/report/ProgramSupportResponse.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/report/package-info.java
  daycan-back/api/src/main/java/com/daycan/api/dto/member/response/statistics/package-info.java
  daycan-back/api/src/main/java/com/daycan/common/response/status/error/DocumentErrorStatus.java
  daycan-back/api/src/main/java/com/daycan/domain/model/DocumentMetaView.java
  daycan-back/api/src/main/java/com/daycan/scheduler/DocumentScheduler.java
  daycan-back/api/src/main/java/com/daycan/service/center/CenterService.java
  daycan-back/api/src/main/java/com/daycan/service/center/StaffService.java
  daycan-back/api/src/main/java/com/daycan/service/document/CareSheetQueryService.java
  daycan-back/api/src/main/java/com/daycan/service/document/CenterDocumentFacade.java
  daycan-back/api/src/main/java/com/daycan/service/document/DocumentService.java
  daycan-back/api/src/main/java/com/daycan/service/document/VitalService.java
  daycan-back/api/src/main/java/com/daycan/service/member/MemberFacade.java
  daycan-back/api/src/main/java/com/daycan/service/member/MemberService.java
Labels: 👨🏻‍🏫 BE - 김수환

#173 Feature/fe/#158 수급자 관리 페이지 api연동
  daycan-front/apps/admin/src/components/EditAuthModal/index.ts
  daycan-front/apps/admin/src/components/EditDeleteAuthModal/EditDeleteAuthModal.css.ts
  daycan-front/apps/admin/src/components/EditDeleteAuthModal/EditDeleteAuthModal.tsx
  daycan-front/apps/admin/src/components/EditDeleteAuthModal/index.ts
  daycan-front/apps/admin/src/components/index.ts
  daycan-front/apps/admin/src/pages/login/hooks/useAdminLoginHook.ts
  daycan-front/apps/admin/src/pages/member-register/MemberRegisterPage.tsx
  daycan-front/apps/admin/src/pages/member-register/components/GuardianInfoSection/GuardianInfoSection.tsx
  daycan-front/apps/admin/src/pages/member-register/components/InfoSectionLayout/InfoSectionLayout.tsx
  daycan-front/apps/admin/src/pages/member-register/components/MemberInfoSection/MemberInfoSection.tsx
  daycan-front/apps/admin/src/pages/member-register/hooks/useImageController.ts
  daycan-front/apps/admin/src/pages/member-register/hooks/useMemberRegisterForm.ts
  daycan-front/apps/admin/src/pages/member/MemberPage.tsx
  daycan-front/apps/admin/src/pages/member/components/DetailCardLayout/DetailCardLayout.tsx
  daycan-front/apps/admin/src/pages/member/components/GuardianDetailContent/GuardianDetailContent.tsx
  daycan-front/apps/admin/src/pages/member/components/HistoryModal/HistoryModal.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItem/MemberDataItem.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItemDetail/MemberDataItemDetail.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataList/MemberDataList.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataListHeader/MemberDataListHeader.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDetailContent/MemberDetailContent.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDetailItemRow/MemberDetailItemRow.tsx
  daycan-front/apps/admin/src/pages/member/constants/member.ts
  daycan-front/apps/admin/src/pages/member/constants/memberDummyData.ts
  daycan-front/apps/admin/src/pages/member/hooks/useMemberFilter.ts
  daycan-front/apps/admin/src/pages/staff/components/StaffDetailContent/StaffDetailContent.tsx
  daycan-front/apps/admin/src/services/auth/index.ts
  daycan-front/apps/admin/src/services/auth/types.ts
  daycan-front/apps/admin/src/services/auth/useAdminAuthMutation.ts
  daycan-front/apps/admin/src/services/image/index.ts
  daycan-front/apps/admin/src/services/image/useUploadImageMutation.ts
  daycan-front/apps/admin/src/services/member/index.ts
  daycan-front/apps/admin/src/services/member/types.ts
  daycan-front/apps/admin/src/services/member/useMemberMutation.ts
  daycan-front/apps/admin/src/services/member/useMemberQuery.ts
  daycan-front/apps/admin/src/utils/dataParser.ts
  daycan-front/apps/admin/src/utils/util.ts
  daycan-front/packages/ui/src/components/Button/Button.tsx
  daycan-front/packages/ui/src/components/Segment/Segment.tsx
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature

#183 Feature/fe/#174 종사자 관리 페이지 수정, 등록 페이지 API연동
  daycan-front/apps/admin/src/components/CareLevelRoleDropDownSelector/CareLevelRoleDropDownSelector.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItem/MemberDataItem.tsx
  daycan-front/apps/admin/src/pages/staff-register/StaffRegisterPage.tsx
  daycan-front/apps/admin/src/pages/staff-register/components/ProfileImageSection/ProfileImageSection.tsx
  daycan-front/apps/admin/src/pages/staff-register/components/StaffFormFields/StaffFormFields.tsx
  daycan-front/apps/admin/src/pages/staff-register/hooks/useImageController.ts
  daycan-front/apps/admin/src/pages/staff-register/hooks/useStaffForm.ts
  daycan-front/apps/admin/src/pages/staff-register/utils/staffForm.ts
  daycan-front/apps/admin/src/pages/staff/StaffPage.tsx
  daycan-front/apps/admin/src/pages/staff/components/StaffDetailContent/StaffDetailContent.tsx
  daycan-front/apps/admin/src/pages/staff/components/StaffList/StaffList.tsx
  daycan-front/apps/admin/src/pages/staff/components/StaffListItem/StaffListItem.tsx
  daycan-front/apps/admin/src/pages/staff/hooks/useStaffFilter.ts
  daycan-front/apps/admin/src/pages/staff/hooks/useStaffModal.ts
  daycan-front/apps/admin/src/services/image/useUploadImageMutation.ts
  daycan-front/apps/admin/src/services/member/types.ts
  daycan-front/apps/admin/src/services/staff/index.ts
  daycan-front/apps/admin/src/services/staff/useStaffMutation.ts
  daycan-front/apps/admin/src/utils/util.ts
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature

#199 Feature/fe/#184 스켈레톤 UI 기록지 작성, 리포트 전송, 수급자 관리, 종사자 관리 페이지 내 ListItem에 적용
  daycan-front/apps/admin/src/components/SkeletonList/SkeletonList.tsx
  daycan-front/apps/admin/src/components/SkeletonList/index.ts
  daycan-front/apps/admin/src/components/SkeletonListItem/SkeletonListItem.tsx
  daycan-front/apps/admin/src/components/SkeletonListItem/index.ts
  daycan-front/apps/admin/src/components/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/CareSheetPage.tsx
  daycan-front/apps/admin/src/pages/care-sheet/components/SkeletonCareSheetList/SkeletonCareSheetList.tsx
  daycan-front/apps/admin/src/pages/care-sheet/components/SkeletonCareSheetList/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/constants/CARE_SHEET_GRID_TEMPLATE.ts
  daycan-front/apps/admin/src/pages/care-sheet/hooks/useCareSheet.ts
  daycan-front/apps/admin/src/pages/member-register/components/InfoSectionRow/InfoSectionRow.tsx
  daycan-front/apps/admin/src/pages/member/MemberPage.tsx
  daycan-front/apps/admin/src/pages/report/ReportPage.tsx
  daycan-front/apps/admin/src/pages/report/hooks/useReport.ts
  daycan-front/apps/admin/src/pages/staff/StaffPage.tsx
  daycan-front/apps/admin/src/router/routes.tsx
  daycan-front/apps/admin/src/services/member/useMemberQuery.ts
  daycan-front/apps/admin/src/services/staff/useStaffQuery.ts
  daycan-front/packages/ui/src/components/SkeletonAnimationBlock/SkeletonAnimationBlock.css.ts
  daycan-front/packages/ui/src/components/SkeletonAnimationBlock/SkeletonAnimationBlock.tsx
  daycan-front/packages/ui/src/components/SkeletonAnimationBlock/index.ts
  daycan-front/packages/ui/src/components/index.ts
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature

#205 Feature/fe/#200 - Sentry 초기 세팅 및 500대 서버 에러 후킹 및 Discord 세팅
  daycan-front/apps/admin/package.json
  daycan-front/apps/admin/src/contexts/QueryProvider.tsx
  daycan-front/apps/admin/src/index.tsx
  daycan-front/apps/admin/src/services/error/handleError.ts
  daycan-front/apps/admin/src/services/error/sentry.ts
  daycan-front/apps/admin/vercel.json
  daycan-front/apps/admin/vite.config.ts
  daycan-front/apps/client/package.json
  daycan-front/apps/client/src/components/SemiCircularGaugeChart/SemiCircularGaugeChart.tsx
  daycan-front/apps/client/src/contexts/QueryProvider.tsx
  daycan-front/apps/client/src/index.tsx
  daycan-front/apps/client/src/pages/daily-report/components/CardLayout/CardLayout.css.ts
  daycan-front/apps/client/src/pages/daily-report/components/CardLayout/CardLayout.tsx
  daycan-front/apps/client/src/pages/daily-report/components/HealthCheckCard/HealthCheckCard.tsx
  daycan-front/apps/client/src/pages/daily-report/components/IndexColumn/IndexColumn.tsx
  daycan-front/apps/client/src/pages/daily-report/components/IndexRow/IndexRow.tsx
  daycan-front/apps/client/src/pages/main/MainPage.tsx
  daycan-front/apps/client/src/pages/main/index.ts
  daycan-front/apps/client/src/services/auth/useAuthMutation.ts
  daycan-front/apps/client/src/services/error/handleError.ts
  daycan-front/apps/client/src/services/error/sentry.ts
  daycan-front/apps/client/src/services/main/useMainQuery.ts
  daycan-front/apps/client/vercel.json
  daycan-front/apps/client/vite.config.ts
  daycan-front/packages/ui/src/assets/svg/stamp-bad.svg
  daycan-front/packages/ui/src/assets/svg/stamp-good.svg
  daycan-front/pnpm-lock.yaml
  daycan-front/pnpm-workspace.yaml
Labels: 👦🏻 FE - 홍규진, ✨ feature

#206 Feature/fe/#204 UI/UX 디테일 수정과 상세보기 Focus기능, Layout Shift문제 수정 && 대체 이미지 통일
  daycan-front/apps/admin/src/assets/images/emptyProfile.png
  daycan-front/apps/admin/src/layout/main/mainLayout.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/components/CareSheetList/CareSheetList.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/components/CareSheetList/CareSheetList.tsx
  daycan-front/apps/admin/src/pages/login/LoginPage.tsx
  daycan-front/apps/admin/src/pages/login/components/ForgotCredentialsModal/ForgotCredentialsModal.tsx
  daycan-front/apps/admin/src/pages/member-register/MemberRegisterPage.tsx
  daycan-front/apps/admin/src/pages/member/components/DetailCardLayout/DetailCardLayout.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataItem/MemberDataItem.tsx
  daycan-front/apps/admin/src/pages/member/components/MemberDataList/MemberDataList.css.ts
  daycan-front/apps/admin/src/pages/member/components/MemberDataList/MemberDataList.tsx
  daycan-front/apps/admin/src/pages/member/constants/memberGrid.ts
  daycan-front/apps/admin/src/pages/report/components/ReportList/ReportList.css.ts
  daycan-front/apps/admin/src/pages/report/components/ReportList/ReportList.tsx
  daycan-front/apps/admin/src/pages/staff-register/StaffRegisterPage.tsx
  daycan-front/apps/admin/src/pages/staff-register/components/ProfileImageSection/ProfileImageSection.tsx
  daycan-front/apps/admin/src/pages/staff/components/StaffDetailContent/StaffDetailContent.tsx
  daycan-front/apps/admin/src/pages/staff/components/StaffList/StaffList.css.ts
  daycan-front/apps/admin/src/pages/staff/components/StaffList/StaffList.tsx
  daycan-front/apps/admin/src/pages/staff/components/StaffListItem/StaffListItem.tsx
  daycan-front/apps/admin/src/pages/staff/constants/staffGrid.ts
  daycan-front/apps/admin/src/styles/scroll.css.ts
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature, ⚙️ refactor, 🎨 style

#248 Feature/fe/#246 - 최종 정책 수정으로 인한 API 명세 수정
  daycan-front/apps/admin/package.json
  daycan-front/apps/admin/src/contexts/QueryProvider.tsx
  daycan-front/apps/admin/src/pages/care-sheet-today/components/CareSheetListItem/CareSheetListItem.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/HomeFunnelStepContainer.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/ConfirmModal/ConfirmModal.css.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/ConfirmModal/ConfirmModal.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/ConfirmModal/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/components/index.ts
  daycan-front/apps/admin/src/pages/care-sheet/funnels/home-funnel/steps/Step1/Step1.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberList/MemberList.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/components/MemberListItem/MemberListItem.tsx
  daycan-front/apps/admin/src/pages/care-sheet/funnels/info-funnel/steps/Step0/Step0.tsx
  daycan-front/apps/admin/src/pages/report/hooks/useReport.ts
  daycan-front/apps/admin/src/services/auth/useAdminAuthMutation.ts
  daycan-front/apps/admin/src/services/instance.ts
  daycan-front/apps/admin/src/services/member/index.ts
  daycan-front/apps/admin/src/services/member/types.ts
  daycan-front/apps/admin/src/services/member/useMemberQuery.ts
  daycan-front/apps/client/src/contexts/QueryProvider.tsx
  daycan-front/apps/client/src/pages/daily-report/constants/iconMapping.tsx
  daycan-front/apps/client/src/pages/main/MainPage.tsx
  daycan-front/apps/client/src/pages/main/components/DailyReportModal/DailyReportModal.tsx
  daycan-front/apps/client/src/pages/main/components/Greeting/Greeting.tsx
  daycan-front/apps/client/src/pages/reports/components/ReportsContent/ReportsContent.tsx
  daycan-front/apps/client/src/pages/reports/hooks/index.ts
  daycan-front/apps/client/src/pages/reports/hooks/useReportDateSelection.ts
  daycan-front/apps/client/src/services/auth/useAuthMutation.ts
  daycan-front/apps/client/src/services/instance.ts
  daycan-front/apps/client/src/services/report/index.ts
  daycan-front/apps/client/src/services/report/types.ts
  daycan-front/apps/client/src/services/report/useReportQuery.ts
  daycan-front/apps/client/src/utils/dateUtils.ts
  daycan-front/packages/ui/src/components/Calendar/Calendar.css
  daycan-front/packages/ui/src/components/Calendar/Calendar.tsx
  daycan-front/pnpm-lock.yaml
Labels: 👦🏻 FE - 홍규진, ✨ feature, 🚨 hotissue

#255 Refactor/fe/#251 수정 삭제 모달 API변동 && 로그인 페이지 하이퍼 링크 수정
  daycan-front/apps/admin/src/components/EditDeleteAuthModal/EditDeleteAuthModal.tsx
  daycan-front/apps/admin/src/pages/login/LoginPage.tsx
  daycan-front/apps/admin/src/services/auth/index.ts
  daycan-front/apps/admin/src/services/auth/types.ts
  daycan-front/apps/admin/src/services/auth/useAdminAuthMutation.ts
  daycan-front/apps/client/src/pages/login/LoginPage.tsx
Labels: 👱🏻‍♂️ FE - 소보길, ✨ feature, ⚙️ refactor
